// pages/_document.js
import { Html, Head, Main, NextScript } from "next/document";
import Script from "next/script";

export default function Document() {
  return (
    <Html lang="en">
      <Head>
        {/* Preload fonts - these are typically auto-generated by Next.js */}
        <link
          rel="preload"
          href="/_next/static/media/042a00f4b3c474b9-s.p.ttf"
          as="font"
          crossOrigin=""
          type="font/ttf"
        />
        <link
          rel="preload"
          href="/_next/static/media/0ddfd6b1e257170f-s.p.ttf"
          as="font"
          crossOrigin=""
          type="font/ttf"
        />
        <link
          rel="preload"
          href="/_next/static/media/a304e72db1b9eeb1-s.p.ttf"
          as="font"
          crossOrigin=""
          type="font/ttf"
        />
        <link
          rel="preload"
          href="/_next/static/media/bf7319866b552d52-s.p.ttf"
          as="font"
          crossOrigin=""
          type="font/ttf"
        />
        <link
          rel="preload"
          href="/_next/static/media/d9908f88b94bd31e-s.p.ttf"
          as="font"
          crossOrigin=""
          type="font/ttf"
        />
        <link
          rel="preload"
          href="/_next/static/media/e326cf415f11af9a-s.p.ttf"
          as="font"
          crossOrigin=""
          type="font/ttf"
        />

        {/* Preload scripts */}
        <link
          rel="preload"
          as="script"
          fetchPriority="low"
          href="/_next/static/chunks/webpack-3a94656ca3367923.js"
        />
        {/* Smartsupp Chat */}
        {/* <Script id="smartsupp-chat" strategy="afterInteractive">
          {`
 var _smartsupp = _smartsupp || {};
_smartsupp.key = '0f7ed07b0e7734e5176ca64f81cbb21f083e549b';
window.smartsupp||(function(d) {
	var s,c,o=smartsupp=function(){ o._.push(arguments)};o._=[];
	s=d.getElementsByTagName('script')[0];c=d.createElement('script');
	c.type='text/javascript';c.charset='utf-8';c.async=true;
	c.src='https://www.smartsuppchat.com/loader.js?';s.parentNode.insertBefore(c,s);
})(document);
          `}
        </Script> */}
      </Head>
      <body className="antialiased">
        <Main />
        <NextScript />
      </body>
    </Html>
  );
}
